require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/admins", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Admin. As you add validations to Admin, be sure to
  # adjust the attributes here as well.

  let(:valid_attributes) {
    {
      username: "Valid Admin Name",
      permission: "Full_control_on_Comment_or_Like",
      user_attributes: {
        email: "admin@example.com",
        password: "password123",
        password_confirmation: "password123"
      }
    }
  }

  let(:invalid_attributes_missing_name) {
    {
      username: "",
      permission: "Full_control_on_Comment_or_Like",
      user_attributes: {
        email: "admin@example.com",
        password: "password123",
        password_confirmation: "password123"
      }
    }
  }

  let(:invalid_attributes_invalid_email) {
    {
      username: "valid Admin name",
      permission: "Full_control_on_Comment_or_Like",
      user_attributes: {
        email: "admin_email",
        password: "password123",
        password_confirmation: "password123"
      }
    }
  }

  let(:invalid_attributes_password_len_5) {
    {
      username: "valid Admin name",
      permission: "Full_control_on_Comment_or_Like",
      user_attributes: {
        email: "admin_email",
        password: "p@ss1",
        password_confirmation: "p@ss1"
      }
    }
  }

  let(:invalid_attributes_password_mismatch) {
    {
      username: "valid Admin name",
      permission: "Full_control_on_Comment_or_Like",
      user_attributes: {
        email: "admin_email",
        password: "password1234",
        password_confirmation: "password123"
      }
    }
  }


  describe "GET request" do
    let!(:admin) { Admin.create! valid_attributes }

    it "/index renders a successful response" do
      get admins_url
      expect(response).to be_successful
    end

    it "/show renders a successful response" do
      get admin_url(admin)
      expect(response).to be_successful
    end

    it "/new renders a successful response" do
      get new_admin_url
      expect(response).to be_successful
    end

    it "/edit renders a successful response" do
      get edit_admin_url(admin)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Admin" do
        expect {
          post admins_url, params: { admin: valid_attributes }
        }.to change(Admin, :count).by(1)
      end

      it "redirects to the created admin" do
        post admins_url, params: { admin: valid_attributes }
        expect(response).to redirect_to(admin_url(Admin.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Admin with missing name" do
        expect {
          post admins_url, params: { admin: invalid_attributes_missing_name }
        }.to change(Admin, :count).by(0)
      end

      it "does not create a new Admin with invalid email" do
        expect {
          post admins_url, params: { admin: invalid_attributes_invalid_email }
        }.to change(Admin, :count).by(0)
      end

      it "does not create a new Admin with password less than 6 characters" do
        expect {
          post admins_url, params: { admin: invalid_attributes_password_len_5 }
        }.to change(Admin, :count).by(0)
      end

      it "does not create a new Admin with password mismatch" do
        expect {
          post admins_url, params: { admin: invalid_attributes_password_mismatch }
        }.to change(Admin, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post admins_url, params: { admin: invalid_attributes_invalid_email }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    let!(:admin) { Admin.create! valid_attributes }

    context "with valid parameters" do
      let(:new_attributes_username_password_change) {
        {
          username: "New Valid Admin Name",
          permission: "Full_control_on_Comment_or_Like",
          user_attributes: {
            email: "newadmin@example.com",
            password: "password123",
            password_confirmation: "password123"
          }
        }
      }

      it "updates the requested admin" do
        patch admin_url(admin), params: { admin: new_attributes_username_password_change }
        admin.reload

        expect(admin.username).to eq("New Valid Admin Name")
        expect(admin.user.email).to eq("newadmin@example.com")
      end

      it "redirects to the admin" do
        patch admin_url(admin), params: { admin: new_attributes_username_password_change }
        admin.reload
        expect(response).to redirect_to(admin_url(admin))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        patch admin_url(admin), params: { admin: invalid_attributes_invalid_email }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    let!(:admin) { Admin.create! valid_attributes }

    it "destroys the requested admin" do
      expect {
        delete admin_url(admin)
      }.to change(Admin, :count).by(-1)
    end

    it "redirects to the admins list" do
      delete admin_url(admin)
      expect(response).to redirect_to(admins_url)
    end
  end
end
